---
title: "moreproteins-alex"
format: pdf
editor: visual
---

## 

```{r}
library(tidyverse)
library(infer)
library(randomForest)
library(tidymodels)
library(modelr)
library(yardstick)
load('data/biomarker-clean.RData')
```

```{r}
## MULTIPLE TESTING
####################

# function to compute tests
test_fn <- function(.df){
  t_test(.df, 
         formula = level ~ group,
         order = c('ASD', 'TD'),
         alternative = 'two-sided',
         var.equal = F)
}

ttests_out <- biomarker_clean %>%
  # drop ADOS score
  select(-ados) %>%
  # arrange in long format
  pivot_longer(-group, 
               names_to = 'protein', 
               values_to = 'level') %>%
  # nest by protein
  nest(data = c(level, group)) %>% 
  # compute t tests
  mutate(ttest = map(data, test_fn)) %>%
  unnest(ttest) %>%
  # sort by p-value
  arrange(p_value) %>%
  # multiple testing correction
  mutate(m = n(),
         hm = log(m) + 1/(2*m) - digamma(1),
         rank = row_number(),
         p.adj = m*hm*p_value/rank)

# select significant proteins
proteins_s1 <- ttests_out %>%
  slice_min(p.adj, n = 10) %>%
  pull(protein)

proteins_s1_new <- ttests_out %>%
  slice_min(p.adj, n = 30) %>%
  pull(protein)
```

```{r}
## RANDOM FOREST
##################

# store predictors and response separately
predictors <- biomarker_clean %>%
  select(-c(group, ados))

response <- biomarker_clean %>% pull(group) %>% factor()

# fit RF
set.seed(101422)
rf_out <- randomForest(x = predictors, 
                       y = response, 
                       ntree = 1000, 
                       importance = T)

# check errors
rf_out$confusion

# compute importance scores
proteins_s2 <- rf_out$importance %>% 
  as_tibble() %>%
  mutate(protein = rownames(rf_out$importance)) %>%
  slice_max(MeanDecreaseGini, n = 10) %>%
  pull(protein)

proteins_s2_new <- rf_out$importance %>% 
  as_tibble() %>%
  mutate(protein = rownames(rf_out$importance)) %>%
  slice_max(MeanDecreaseGini, n = 30) %>%
  pull(protein)
```

```{r}
## LOGISTIC REGRESSION
#######################

# select subset of interest
proteins_sstar <- intersect(proteins_s1, proteins_s2)
proteins_sstar_new <- intersect(proteins_s1_new, proteins_s2_new)

biomarker_sstar <- biomarker_clean %>%
  select(group, any_of(proteins_sstar)) %>%
  mutate(class = (group == 'ASD')) %>%
  select(-group)

biomarker_sstar_new <- biomarker_clean %>%
  select(group, any_of(proteins_sstar_new)) %>%
  mutate(class = (group == 'ASD')) %>%
  select(-group)

# partition into training and test set
set.seed(101422)
biomarker_split <- biomarker_sstar %>%
  initial_split(prop = 0.8)

biomarker_split_new <- biomarker_sstar_new %>%
  initial_split(prop = 0.8)

# fit logistic regression model to training set
fit <- glm(class ~ ., 
           data = training(biomarker_split), 
           family = 'binomial')

fit_new <- glm(class ~ ., 
           data = training(biomarker_split_new), 
           family = 'binomial')

# evaluate errors on test set
class_metrics <- metric_set(sensitivity, specificity, accuracy)
class_metrics_new <- metric_set(sensitivity, specificity, accuracy)

test_results <- testing(biomarker_split) %>%
  add_predictions(fit, type = "response") %>%
  mutate(           
    pred_factor = as.factor(pred > 0.5),
    class_factor = as.factor(class)
  )

# Evaluate
class_metrics(
  data = test_results,
  truth = class_factor,
  estimate = pred_factor,
  .pred = pred,
  event_level = "second"
)

# Larger Initial Protein Selection Test Results (30)
test_results_new <- testing(biomarker_split_new) %>%
  add_predictions(fit_new, type = "response") %>%
  mutate(           
    pred_factor = as.factor(pred > 0.5),
    class_factor = as.factor(class)
  )

# Evaluate
class_metrics_new(
  data = test_results_new,
  truth = class_factor,
  estimate = pred_factor,
  .pred = pred,
  event_level = "second"
)
```
